//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Tests.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class People {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal People() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("Testing.Tests.Data.People", typeof(People).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaron
        ///Adam
        ///Alan
        ///Albert
        ///Alex
        ///Alexander
        ///Alexandra
        ///Alfred
        ///Alice
        ///Alicia
        ///Alison
        ///Allan
        ///Allen
        ///Allison
        ///Alvin
        ///Amanda
        ///Amy
        ///Andrea
        ///Andrew
        ///Angela
        ///Anita
        ///Ann
        ///Anna
        ///Anne
        ///Annette
        ///Annie
        ///Anthony
        ///April
        ///Arlene
        ///Arnold
        ///Arthur
        ///Ashley
        ///Audrey
        ///Barbara
        ///Barry
        ///Becky
        ///Ben
        ///Benjamin
        ///Bernard
        ///Bernice
        ///Beth
        ///Betsy
        ///Betty
        ///Beverly
        ///Bill
        ///Billie
        ///Billy
        ///Bob
        ///Bobby
        ///Bonnie
        ///Brad
        ///Bradley
        ///Brandon
        ///Brenda
        ///Brent
        ///Brett
        ///Brian
        ///Brooke
        ///Bruce
        ///Bryan
        ///Calvin
        ///Cameron
        ///Carl
        ///Carla
        ///Carlos
        ///Carmen
        ///Carol
        ///Carole
        ///C [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FirstNames {
            get {
                return ResourceManager.GetString("FirstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male
        ///Female.
        /// </summary>
        public static string Genders {
            get {
                return ResourceManager.GetString("Genders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbott
        ///Abrams
        ///Adams
        ///Adcock
        ///Adkins
        ///Adler
        ///Albright
        ///Aldridge
        ///Alexander
        ///Alford
        ///Allen
        ///Allison
        ///Allred
        ///Alston
        ///Anderson
        ///Andrews
        ///Anthony
        ///Archer
        ///Armstrong
        ///Arnold
        ///Arthur
        ///Ashley
        ///Atkins
        ///Atkinson
        ///Austin
        ///Avery
        ///Aycock
        ///Ayers
        ///Bailey
        ///Baird
        ///Baker
        ///Baldwin
        ///Ball
        ///Ballard
        ///Banks
        ///Barbee
        ///Barber
        ///Barbour
        ///Barefoot
        ///Barker
        ///Barnes
        ///Barnett
        ///Barr
        ///Barrett
        ///Barry
        ///Bartlett
        ///Barton
        ///Bass
        ///Batchelor
        ///Bates
        ///Bauer
        ///Baxter
        ///Beach
        ///Bean
        ///Beard
        ///Beasley
        ///Beatty
        ///Beck
        ///Becker
        ///Bell
        ///Bender
        ///Bennett
        ///Benson
        ///Be [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
    }
}
